server:
  port: 5000

#  server:
#    tomcat:
#      max-swallow-size: 100MB #重要的一行，修改tomcat的吞吐量
spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3316/lab_system
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0
jwt:
  secret: privatekey
  expire: 1800 # 单位秒 30分钟 == 30*60秒
  header: Authorization





